# Gains for the Proportional-Derivative Joint Space Controller
# P and D gains for each axis.
jointspace_controller: 
 #proportional
 gains_p: [50, 612.71801, 612.71801, 150, 40, 5]
 #gains_p: [50, 612.71801, 612.71801, 150, 40, 50]
 #gains_p: [1000, 1200.71801, 1200.71801, 1500, 400, 50]

 
 #derivative
 gains_d: [100, 75, 75, 73, 15, 5]
 #gains_d: [100, 75, 75, 73, 15, 50]

 # Desired position in deg [J1, J2, J3, J4, J5, J6], e.g. [90, -45, 30, -70, 40, 40]
 # Home: [0, -90, 0, -90, 0, 0]
 # goal of cartesian space 
 #goal: [0, -45, 90, -135, 90, -90]

# goal of joint space controller
 goal: [0, -90, 90, 0, 90, 0]
 time: 10.0